### ISSUE TITLE
AttributeError when looking for the 'neighbourhoods' neighbourhood

### ISSUE THREAD

**Issue by colons** [rkhleics/police-api-client-python#1]
``` python
>>> from police_api import PoliceAPI
>>> api = PoliceAPI()
>>> api.get_force('leicestershire').get_neighbourhood('neighbourhoods').name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "police_api/resource.py", line 34, in __getattr__
    self._make_api_request()
  File "police_api/resource.py", line 40, in _make_api_request
    self._hydrate(self._response_data)
  File "police_api/resource.py", line 11, in _hydrate
    setattr(self, field, hydrate_field(data.get(field)))
AttributeError: 'list' object has no attribute 'get'
```

This is a result of unfortunate [namespace](http://data.police.uk/docs/method/neighbourhoods/) [ambiguity](http://data.police.uk/docs/method/neighbourhood/) in the API, but this client exists with the explicit aim of abstracting such issues away. This should be handled. I'm not sure exactly how.

One solution would be to raise a new `ImpossibleAPICall` (probably could be named better) `APIError` subclass. It's the kind of thing people are going to want to be able to handle explicitly should they ever run into it.

**Comment by colons** [comment]
@robgolding63 I'm looking at actually implementing this, but I'm not sure where the best place would be. `BaseService.request()` is the closest place in the client to where the API ambiguity at the heart of this issue is. Unfortunately, that method has no way of knowing if a request for `[force]/neighbourhoods` is looking for a neighbourhood or a list of neighbourhoods.

That leaves us with the option that something in the `Neighbourhood` class is going to have to be aware that a neighbourhood called `'neighbourhoods'` is a problem even though requests for boundaries, events, etc., for such a neighbourhood would be completely legitimate.

**Comment by robgolding** [comment]
@colons I think implementing it in the `Neighbourhood` class is the only thing we can reasonably do. Your suggestion of an `ImpossibleAPICall` (or similar) is a good one, and I think we should go with that so it's clear exactly what the problem is, rather than faking a `404` (which is, arguably, what the API should be doing).

**Comment by robgolding** [comment]
:+1:

**Comment by colons** [comment]
You'll like this.

``` python
>>> from police_api import PoliceAPI
>>> api = PoliceAPI()
>>> api.get_neighbourhood('leicestershire', 'neighbourhoods')
Traceback (most recent call last):
[...]
NeighbourhoodsNeighbourhoodException: It is impossible to get information about the 'neighbourhoods' neighbourhood due to a conflict between http://data.police.uk/docs/method/neighbourhoods/ and http://data.police.uk/docs/method/neighbourhood/.
>>> api.get_neighbourhood('leicestershire', 'neighbourhoods', preload=True)
Traceback (most recent call last):
[...]
AttributeError: 'list' object has no attribute 'get'
```

┐(-｡-;)┌
